# Author
author:
  name: Natesh Narain
  email: nnaraindev@gmail.com
  url: nnarain.github.io

# Site settings
title: Natesh's Dev Blog!
description: >
    A place where I can drop code snippets and how-to's of various projects I'm working on.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nnarain.github.io" # the base hostname & protocol for your site

collections:
  learn:
    output: true
    permalink: /:collection/:name
  makes:
    output: true
    permalink: /:collection/:name
  projects:
    output: true
    permalink: /:collection/:name

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# social media
github_username:  nnarain
github_url: https://github.com/nnarain
youtube_username: nnaraindev
youtube_url: https://www.youtube.com/channel/UCVYy1Jiww7YAsgEFD2CSQSw
linkedin_url: https://www.linkedin.com/in/natesh-narain/

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

highlighter: rouge

# page settings
paginate: 5
paginate_path: "/blog/page:num"

enableTags: true
tagarray: []

# plugins
plugins: [jekyll-paginate, jekyll-gist]
