# Site settings
author: Natesh Narain
title: Natesh's Dev Blog!
email: nnaraindev@gmail.com
description: >
    A place where I can drop code snippets and how-to's of various projects I'm working on.
    Anything from C to Assembler to Graphics to Web dev!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nnarain.github.io" # the base hostname & protocol for your site

# social media
github_username:  nnarain
github_url: https://github.com/nnarain
youtube_username: nnaraindev
youtube_url: https://www.youtube.com/channel/UCVYy1Jiww7YAsgEFD2CSQSw

# analytics
google_analytics: UA-107298548-1

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

highlighter: rouge

# page settings
paginate: 5
paginate_path: "/blog/page:num"

enableTags: true
tagarray: []

# gems
gems: [jekyll-paginate, jekyll-gist]
